### ISSUE TITLE
Experimental correlation function notebook for Session 1

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#42]
Introduce correlation function as the ultimate summary statistic. Compute it for a small sample of SDSS galaxies, get something very noisy. Invite comment. 

The idea is to set up some of the cosmology stuff in Week 3, and also produce a set of summary statistics that _look like the Cepheid dataset_. Then, we can talk about the meaning and interpretation of the error bars...

**Comment by cpadavis** [comment]
Are you sure you don't want to use the Landy-Szalay estimator for the correlation function? You do need to compute an extra set of paircounts (DR) but it is pretty 'industry standard' for real space correlation function computation.

Another thing is you usually want your randoms to be bigger than your dataset when doing correlation functions -- often at least 10x bigger. In your case here it isn't too important since you're doing a square patch on the sky that is small enough to be approximately flat, but if you use a more complicated footprint it can really matter -- you really want survey geometry to not be limited by shot noise from your random samples, which are relatively cheap to compute! It also isn't too clear from the text why you need randoms at all to compute the correlation function. (Like one sentence "correlations of randoms distributed uniformly over survey footprint can account for spurious effects in the correlation function due to weird survey geometry" would be great.)

**Comment by drphilmarshall** [comment]
Thanks Chris! I'll add some text as you suggest. I chose the most basic possible estimator because a) it's easier to see where it comes from and b) it gives additional possibilities to the active part of this notebook, which is the think-pair-share "Q" at the bottom. I love that you have started the in-class exercises _before the quarter has started_ ;-)
