### ISSUE TITLE
Notebookify session 5

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#72]
@drphilmarshall has offered to distill the whiteboard jumble we generated into a notebook. Re-assign to me for review once you're had a first pass. Hopefully in the process we'll decide how best to include some of the pesky truncation-related variables in the PGM.

**Comment by drphilmarshall** [comment]
Good, thanks Adam! I think the "derive this together" format worked well for this topic, because they are tricky problems to engage with - so we have to think about how to structure the notebook. I think `%load`-ing markdown files for each complication, and also `Image()` displaying each new PGM will work well. Glad you assigned this to "Someday"!

**Comment by abmantz** [comment]
subsumed by some combination of #98 and #102
