### ISSUE TITLE
Update schedule, summary, room booking, goals

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#83]
What days are we teaching in winter 2017?
What course summary and goals do we need to define?

**Comment by drphilmarshall** [comment]
@abmantz Here's [PHYSICS 366 on the Stanford website](https://explorecourses.stanford.edu/search?view=catalog&filter-coursestatus-Active=on&page=0&catalog=&academicYear=&q=PHYSICS+366&collapse=):

> PHYSICS 366: Special Topics in Astrophysics: Statistical Methods
> 
> Existing and emerging statistical techniques and their application to astronomical surveys and cosmological data analysis. Topics covered will include statistical frameworks (Bayesian inference and frequentist statistics), numerical methods including Markov Chain Monte Carlo, and machine learning applied to classification and regression. Hands on activities based on open-source software in python. Recommended prerequisites: PHYSICS 260 and 261, or equivalent. Familiarity with Python coding and basic statistics at level of STATS 116. This course runs for the first five weeks of the quarter.
> 
> Schedule for PHYSICS 366
> 2016-2017 Winter
> PHYSICS 366 | 2 units | Class # 32621 | Section 01 | Grading: Letter or Credit/No Credit | LEC 
> 01/09/2017 - 03/17/2017 Thu 3:00 PM - 4:50 PM at Hewlett Teaching Center 102 with Marshall, P. (PI) 
> Instructors: Marshall, P. (PI) 
> Notes: 2-unit, 10-week special topics course.

There's a few things here that don't look optimal:
- 10 sessions, 110 mins per week
- Only one instructor listed
- Hewlett 102
- Blurb says the course only runs for 5 weeks
- No link to GitHub repo

**Comment by abmantz** [comment]
Indeed, the important things being the number of weeks and the room.

@rhw , do you know whether it's possible to change the course to 10 weeks at this point?

We had also talked about the desirability of getting a room which is actually set up for collaborative work, but I'm not sure who in the dept. handles this.

**Comment by rhw** [comment]
The course is indeed scheduled for 10 weeks (once per week).  It looks like the blurb did not get updated.  You should edit the blurb and we can send to Elva to update.  We can also ask Elva if there is a possibility for a better room.

**Comment by abmantz** [comment]
Ah, I misread the first time. Currently it says the course runs 10 weeks, but only meets once per week. I thought we had all agreed that it should be 10 weeks meeting twice per week. Right?

**Comment by drphilmarshall** [comment]
Yes, we had agreed that: the current session length is quite long, so
perhaps we could split them in two?
I don't mind if we stick with one long session, but would be interested to
hear what you think about attention span, gruellingness etc.

**Comment by abmantz** [comment]
I thought the consensus was that we needed ~2x as much actual class time. Otherwise, we're not really in a different position than we were last term. If I remember, this was also what the students themselves said they would have preferred in our survey. (But it might run afoul of the 2-credit assignment.)

As far as attention spans, my hope was that incorporating some collaborative work during class, as we brainstormed about, would break things up enough.

**Comment by abmantz** [comment]
I just had a chat with Pat B. and Jonny in the dept office, and got some useful information.
1. Enrollment starts at the end of the month, so have not much time to sort this out.
2. We cannot change the number of credits (but IMAO that's not the end of the world).
3. Jonny will check whether we can change to an active-learning-ready room for T,Th 3:00-4:20 (twice a week for half the time, instead of almost 2 hours once a week), and if not will try to come up with some alternatives that get us into a better room. I'll forward these when I get them.

**Comment by abmantz** [comment]
@drphilmarshall please respond to the offline email thread regarding room options sooner rather than later.

**Comment by abmantz** [comment]
Room and class time is now handled: Tu,Th 3:00-4:20 in a flex room, Building 380 Room 381T (capacity 22). This closes #76).

Remaining, and presumably needed by the end of the month when enrollment starts:
- [x] getting the blurb in the course book updated

**Comment by drphilmarshall** [comment]
Excellent work, Adam - thank you very much! Looks like we are all set for
T,Th 3:00-4:20 and in a nice room for 22 people. I look forward to
switching from inky fingers to chalky fingers ;-)
